name: Build the site
on:
  push:
    branches: ["master"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: npm

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      - name: Inject page dates
        run: |
          for src in pages/*/index.html; do
            PAGE_DIR="$(dirname "$src")"
            LAST_DATE="$(git log -1 --date=format:%Y-%m-%dT%H:%M:%SZ --format=%cd -- "$PAGE_DIR")"
            sed -i -e "s|__LAST_DATE__|${LAST_DATE}|g" "$src"
          done

          CURRENT_DATE=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          grep -rl 'CURRENT_DATE' . | xargs sed -i "s|__CURRENT_DATE__|$CURRENT_DATE|g"

      - run: |
          npm ci
          npx tsc --build
          npx vite build --base "${{ steps.pages.outputs.base_path }}"

      - name: Sanitize referrer policy
        run: |
          ZIP="https://github.com/altbdoor/clean-links/releases/latest/download/clean-links-linux.tgz"
          curl --remote-name --location "$ZIP"
          tar xzf clean-links-linux.tgz
          ./clean-links run --fix-all ./dist/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: "./dist"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
